#!/usr/bin/envy bash

#SSH Client Configuration
Host *

PasswordAuthentication no
IdentityFile ~/.ssh/school
SendEnv LANG LC_*
HashknownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredintials no
